---
title: "Programação"
---

</br>

Primeiro dia - *02/12/2024*  

</br>


14:00 - 14:10 - **Abertura**

-   *Priscilla Prudente do Amaral*

14:10 - 14:30 h - **O estado da arte da pesquisa no CEMAVE em 2024**

-   *Marcos de Sousa Fialho*  

14:30 - 14:50 h - **Mata Atlântica sob ameaça: qual é a percepção da sociedade?**

-   *Karine Resende Corrêa Florentino* 

</br>

14:50 - 15:00 h - *Intervalo*  

</br>


15:00 - 15:30 h - **Solturas experimentais do pintassigo-do-nordeste**  

-   *Ulisses Borges Soares Marques*  

15:30 - 16:00 h - **Monitoramento de *Zenaida auriculata* na APA Chapada do Araripe**  

-   *Antônio Emanuel Barreto Alves de Souza*  


</br>

</br>

Segundo dia - *03/12/2024*  

</br>

</br>

14:00 - 14:30 h - **Py-son: monitorando a paisagem sonora**

-   *Zander Augusto Spigolini Vilaça*  

14:30 - 15:00 h - **Da biologia da nidificação à ecologia funcional de aves: experiências e perspectivas**  

-   *Sara Miranda Almeida*  

</br>

15:00 - 15:15 h - *Intervalo*  

</br>


15:15 - 16:00 h - **Diversidade e detectabilidade de aves em um gradiente de estrutura de vegetação no Parque Nacional Grande Sertão Veredas, MG**  

-   *Rodolpho Credo Rodrigues*  



